### ISSUE TITLE
add a sample to FodyAddinSamples

### ISSUE THREAD

**Issue by SimonCropp** [Epoque1/Mimick.Fody#1]
hey @Epoque1  

might be helpful to add a sample here https://github.com/Fody/FodyAddinSamples/tree/master/Samples

**Comment by Epoque1** [comment]
Hi Simon,

I have put together a sample project, however I'm unable to push a new branch to the FodyAddinSamples repository for a merge request. Do I need write access to the repository?

Thanks

**Comment by SimonCropp** [comment]
you need to fork and create a PR https://help.github.com/articles/about-pull-requests/

**Comment by Epoque1** [comment]
Sample is now merged, thanks. I'll close this issue.
