### ISSUE TITLE
Fody Error

### ISSUE THREAD

**Issue by StevenRasmussen** [Epoque1/Mimick.Fody#3]
I just downloaded and installed the nuget package. I've added the `<Mimick />` node to the FodyWeavers.xml file and then I just try compiling the project and I get a Fody error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver C:\Users\steve\.nuget\packages\mimick.fody\1.0.1\build\..\netclassicweaver\Mimick.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 185
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 108
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Cannot resolve a reference to IInjectAfterInitializer in any of 'R365.Application.dll, netstandard.dll, Microsoft.Extensions.DependencyInjection.Abstractions.dll, R365.Domain.dll, Microsoft.AspNetCore.Hosting.Abstractions.dll, Microsoft.WindowsAzure.Storage.dll, NodaTime.dll, Microsoft.AspNetCore.Mvc.Core.dll, EPPlus.dll, System.ComponentModel.Annotations.dll, Microsoft.Extensions.Logging.Abstractions.dll, Microsoft.Extensions.Identity.Core.dll, Newtonsoft.Json.dll, AutoMapper.dll, Refit.dll, MethodDecorator.dll, Microsoft.Extensions.Primitives.dll, Microsoft.Net.Http.Headers.dll, Microsoft.AspNetCore.Http.Abstractions.dll, System.Runtime.dll'
Type:
System.MissingMemberException
StackTrace:
   at Mimick.Fody.ReferenceFinder.ResolveType(String name, Boolean full, Boolean throws) in C:\projects\mimick-fody\Mimick.Fody\ReferenceFinder.cs:line 246
   at Mimick.Fody.ReferenceFinder.InitializeReferencedMembers() in C:\projects\mimick-fody\Mimick.Fody\ReferenceFinder.cs:line 159
   at ModuleWeaver.Execute() in C:\projects\mimick-fody\Mimick.Fody\ModuleWeaver.cs:line 47
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 181
Source:
Mimick.Fody
TargetSite:
Mono.Cecil.TypeReference ResolveType(System.String, Boolean, Boolean)
	R365.Application		1

**Comment by Epoque1** [comment]
This seems to be an issue when the dependency is added to the project but not used. I believe as part of the compile process, any unused dependencies are optimized out, so what's happening is the reference to Mimick.dll is being removed.

I believe some Fody dependencies fix this by making it mandatory to add a module-level attribute. Instead, you can fix this by simply adding a reference to `IFrameworkContext` anywhere in your application and the DLL should be included in the build process.

Please let me know if this helps!

**Comment by StevenRasmussen** [comment]
That did it!  Thanks!  Closing this issue.
