### ISSUE TITLE
CacheAttribute Id

### ISSUE THREAD

**Issue by killermoon** [Epoque1/Mimick.Fody#5]
Hi, 
the cache attribute key (or id) is currently set with the parameter of the method and not based on the method name. 

See 
 private string GetHash(object[] values)
        {
            var merged = Encoding.UTF8.GetBytes(string.Join("_", values.Where((p, i) => accepts[i]).Select(p => p?.ToString()?.Replace('_', '.') ?? "null")));
            Console.WriteLine(merged);
            var hash = sha256.ComputeHash(merged);
            return Convert.ToBase64String(hash);
        }

If must be something like this 
        private string GetHash(string methodName, object[] values)
        {
            var merged = Encoding.UTF8.GetBytes(string.Join(methodName, "_", values.Where((p, i) => accepts[i]).Select(p => p?.ToString()?.Replace('_', '.') ?? "null")));
            Console.WriteLine(merged);
            var hash = sha256.ComputeHash(merged);
            return Convert.ToBase64String(hash);
        }

Then you should have something unique (depending on the method name) . Is it possible to change it ?

**Comment by Epoque1** [comment]
Hi there,

Apologies for not getting back sooner on this, for some reason GitHub unsubscribed me from receiving any notifications so I wasn't aware an issue was raised!

The `Cached` attribute is actually scoped to multi-instance, which means that a new `CachedAttribute` instance is created per member per instance of the object type. This means that a fresh cache will exist for each member which is decorated with the attribute, so no need to include the method name in the key.

Does this answer this issue?

Thanks
