### ISSUE TITLE
Version warning

### ISSUE THREAD

**Issue by ebudai** [Epoque1/Mimick.Fody#6]
I am using Mimick in a project with serveral other weavers.  I am getting this warning when building:

MSBUILD : warning FodyVersionMismatch: Fody: Weavers should reference at least the current major version of Fody (version 6). The weaver in Mimick.Fody references version 3. This may result in incompatibilities at build time such as MissingMethodException being thrown.

Are there plans to update the project to Fody 6?

**Comment by Panallox** [comment]
Hi there,

There's currently no plans to upgrade the Fody version, instead I've been focusing efforts on building a separate AOP library which removes the dependency on the Fody framework. If and when the new library is released, it will likely make the Mimick.Fody library redundant (however it will remain available for those not wanting to mix Fody and the new library)

The status of the new library is near-completion, being in the testing stage.

Thanks
